In [2]:
import pandas as pd
import numpy as np

In [8]:
results = pd.read_csv('/Users/liyunxiao/Desktop/QMSS applied data analysis/takehome exercise/Take_home_exercise_4file/data/results_副本.csv')
races = pd.read_csv('/Users/liyunxiao/Desktop/QMSS applied data analysis/takehome exercise/Take_home_exercise_4file/data/races_副本.csv')
drivers = pd.read_csv('/Users/liyunxiao/Desktop/QMSS applied data analysis/takehome exercise/Take_home_exercise_4file/data/drivers_副本.csv')
constructors = pd.read_csv('/Users/liyunxiao/Desktop/QMSS applied data analysis/takehome exercise/Take_home_exercise_4file/data/constructors_副本.csv') 
driver_standings = pd.read_csv('/Users/liyunxiao/Desktop/QMSS applied data analysis/takehome exercise/Take_home_exercise_4file/data/driver_standings_副本.csv') 
constructor_standings = pd.read_csv('/Users/liyunxiao/Desktop/QMSS applied data analysis/takehome exercise/Take_home_exercise_4file/data/constructor_standings_副本.csv')  
qualifying = pd.read_csv('/Users/liyunxiao/Desktop/QMSS applied data analysis/takehome exercise/Take_home_exercise_4file/data/qualifying_副本.csv')

In [10]:
print("results:", results.shape)
print("races:", races.shape)
print("drivers:", drivers.shape)
print("constructors:", constructors.shape)
print("driver_standings:", driver_standings.shape)
print("constructor_standings:", constructor_standings.shape)
print("qualifying:", qualifying.shape)

# Preview data
print("\nResults preview:")
display(results.head())

print("\nRaces preview:")
display(races.head())

print("\nDriver standings preview:")
display(driver_standings.head())

print("\nQualifying preview:")
display(qualifying.head())

# Check columns
print("results columns:")
print(results.columns.tolist())

print("\nraces columns:")
print(races.columns.tolist())

print("\ndriver_standings columns:")
print(driver_standings.columns.tolist())

print("\nconstructor_standings columns:")
print(constructor_standings.columns.tolist())

print("\nqualifying columns:")
print(qualifying.columns.tolist())

results: (26759, 18)
races: (1125, 18)
drivers: (861, 9)
constructors: (212, 5)
driver_standings: (34863, 7)
constructor_standings: (13391, 7)
qualifying: (10494, 9)

Results preview:

,resultId,raceId,driverId,constructorId,number,grid,position,positionText,positionOrder,points,laps,time,milliseconds,fastestLap,rank,fastestLapTime,fastestLapSpeed,statusId
0,1,18,1,1,22,1,1,1,1,10.0,58,1:34:50.616,5690616,39,2,1:27.452,218.300,1
1,2,18,2,2,3,5,2,2,2,8.0,58,+5.478,5696094,41,3,1:27.739,217.586,1
2,3,18,3,3,7,7,3,3,3,6.0,58,+8.163,5698779,41,5,1:28.090,216.719,1
3,4,18,4,4,5,11,4,4,4,5.0,58,+17.181,5707797,58,7,1:28.603,215.464,1
4,5,18,5,1,23,3,5,5,5,4.0,58,+18.014,5708630,43,1,1:27.418,218.385,1

Races preview:

,raceId,year,round,circuitId,name,date,time,url,fp1_date,fp1_time,fp2_date,fp2_time,fp3_date,fp3_time,quali_date,quali_time,sprint_date,sprint_time
0,1,2009,1,1,Australian Grand Prix,2009-03-29,06:00:00,http://en.wikipedia.org/wiki/2009_Australian_G...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N
1,2,2009,2,2,Malaysian Grand Prix,2009-04-05,09:00:00,http://en.wikipedia.org/wiki/2009_Malaysian_Gr...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N
2,3,2009,3,17,Chinese Grand Prix,2009-04-19,07:00:00,http://en.wikipedia.org/wiki/2009_Chinese_Gran...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N
3,4,2009,4,3,Bahrain Grand Prix,2009-04-26,12:00:00,http://en.wikipedia.org/wiki/2009_Bahrain_Gran...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N
4,5,2009,5,4,Spanish Grand Prix,2009-05-10,12:00:00,http://en.wikipedia.org/wiki/2009_Spanish_Gran...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N

Driver standings preview:

   driverStandingsId  raceId  driverId  points  position positionText  wins
0                  1      18         1    10.0         1            1     1
1                  2      18         2     8.0         2            2     0
2                  3      18         3     6.0         3            3     0
3                  4      18         4     5.0         4            4     0
4                  5      18         5     4.0         5            5     0

Qualifying preview:

,qualifyId,raceId,driverId,constructorId,number,position,q1,q2,q3
0,1,18,1,1,22,1,1:26.572,1:25.187,1:26.714
1,2,18,9,2,4,2,1:26.103,1:25.315,1:26.869
2,3,18,5,1,23,3,1:25.664,1:25.452,1:27.079
3,4,18,13,6,2,4,1:25.994,1:25.691,1:27.178
4,5,18,2,2,3,5,1:25.960,1:25.518,1:27.236

results columns:
['resultId', 'raceId', 'driverId', 'constructorId', 'number', 'grid', 'position', 'positionText', 'positionOrder', 'points', 'laps', 'time', 'milliseconds', 'fastestLap', 'rank', 'fastestLapTime', 'fastestLapSpeed', 'statusId']

races columns:
['raceId', 'year', 'round', 'circuitId', 'name', 'date', 'time', 'url', 'fp1_date', 'fp1_time', 'fp2_date', 'fp2_time', 'fp3_date', 'fp3_time', 'quali_date', 'quali_time', 'sprint_date', 'sprint_time']

driver_standings columns:
['driverStandingsId', 'raceId', 'driverId', 'points', 'position', 'positionText', 'wins']

constructor_standings columns:
['constructorStandingsId', 'raceId', 'constructorId', 'points', 'position', 'positionText', 'wins']

qualifying columns:
['qualifyId', 'raceId', 'driverId', 'constructorId', 'number', 'position', 'q1', 'q2', 'q3']

## 2.Build a modeling dataset

In [13]:
# Rename columns in standings tables to avoid name conflicts
driver_standings_renamed = driver_standings.rename(columns={
    "points": "driver_points",
    "position": "driver_standings_pos",
    "wins": "driver_wins"
})

constructor_standings_renamed = constructor_standings.rename(columns={
    "points": "constructor_points",
    "position": "constructor_standings_pos",
    "wins": "constructor_wins"
})

# Merge race-level information into results
model_df = results.merge(
    races[["raceId", "year", "round", "name", "date"]],
    on="raceId",
    how="left"
)

# Merge driver standings into the modeling dataset
model_df = model_df.merge(
    driver_standings_renamed[["raceId", "driverId", "driver_points", "driver_standings_pos", "driver_wins"]],
    on=["raceId", "driverId"],
    how="left"
)

# Merge constructor standings into the modeling dataset
model_df = model_df.merge(
    constructor_standings_renamed[["raceId", "constructorId", "constructor_points", "constructor_standings_pos", "constructor_wins"]],
    on=["raceId", "constructorId"],
    how="left"
)

# Rename qualifying position column
qualifying_renamed = qualifying.rename(columns={
    "position": "quali_position"
})

# Merge qualifying information into the modeling dataset
model_df = model_df.merge(
    qualifying_renamed[["raceId", "driverId", "constructorId", "quali_position"]],
    on=["raceId", "driverId", "constructorId"],
    how="left"
)

In [15]:
# Create a binary target variable for podium finish
model_df["target"] = (model_df["positionOrder"] <= 3).astype(int)

# Check the shape and preview the merged dataset
print("Modeling dataset shape:", model_df.shape)
model_df.head()

# Inspect key modeling columns
selected_cols = [
    "raceId", "driverId", "constructorId", "year", "round",
    "grid", "positionOrder", "target",
    "driver_points", "driver_standings_pos", "driver_wins",
    "constructor_points", "constructor_standings_pos", "constructor_wins",
    "quali_position"
]

model_df[selected_cols].head()

# Check missing values in key columns
missing_summary = model_df[selected_cols].isna().sum().sort_values(ascending=False)
print(missing_summary)

Modeling dataset shape: (26759, 30)
quali_position               16275
constructor_points            1867
constructor_standings_pos     1867
constructor_wins              1867
driver_points                  469
driver_standings_pos           469
driver_wins                    469
raceId                           0
driverId                         0
constructorId                    0
year                             0
round                            0
grid                             0
positionOrder                    0
target                           0
dtype: int64

In [16]:
# Select feature columns for modeling
feature_cols = [
    "grid",
    "driver_points",
    "driver_standings_pos",
    "driver_wins",
    "constructor_points",
    "constructor_standings_pos",
    "constructor_wins",
    "quali_position",
    "year",
    "round"
]

# Keep only the columns needed for modeling
model_data = model_df[[
    "raceId",
    "driverId",
    "constructorId",
    "target"
] + feature_cols].copy()

# Fill missing values in numeric features
model_data["driver_points"] = model_data["driver_points"].fillna(0)
model_data["driver_wins"] = model_data["driver_wins"].fillna(0)
model_data["constructor_points"] = model_data["constructor_points"].fillna(0)
model_data["constructor_wins"] = model_data["constructor_wins"].fillna(0)

model_data["driver_standings_pos"] = model_data["driver_standings_pos"].fillna(99)
model_data["constructor_standings_pos"] = model_data["constructor_standings_pos"].fillna(99)
model_data["quali_position"] = model_data["quali_position"].fillna(99)

In [19]:
# Define feature and target
X = model_data[feature_cols]
y = model_data["target"]

from sklearn.model_selection import train_test_split

# split data into training and testing sets
X_train, X_test, y_train, y_test, meta_train, meta_test = train_test_split(
    X,
    y,
    model_data[["raceId", "driverId", "constructorId"]],
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [23]:
# Print train and test shapes
print("X_train shape:", X_train.shape)
print("X_test shape:", X_test.shape)
print("y_train shape:", y_train.shape)
print("y_test shape:", y_test.shape)

X_train shape: (21407, 10)
X_test shape: (5352, 10)
y_train shape: (21407,)
y_test shape: (5352,)

# Create two (2) new tables in your own database where you'll store the predictions from each model for this exercise.

In [25]:
import sqlite3

# connet to a SQLite database
conn = sqlite3.connect('f1_predictions.db')
cursor = conn.cursor()

In [26]:
# Create a table for the logistic regression model predicitons
cursor.execute("""
CREATE TABLE IF NOT EXISTS predictions_logreg (
    raceId INTEGER,
    driverId INTEGER,
    constructorId INTEGER,
    actual_label INTEGER,
    predicted_label INTEGER,
    predicted_probability REAL,
    model_name TEXT,
    run_id TEXT,
    prediction_timestamp TEXT
)
""")

In [27]:
# Create a table for random forest predictions
cursor.execute("""
CREATE TABLE IF NOT EXISTS predictions_rf (
    raceId INTEGER,
    driverId INTEGER,
    constructorId INTEGER,
    actual_label INTEGER,
    predicted_label INTEGER,
    predicted_probability REAL,
    model_name TEXT,
    run_id TEXT,
    prediction_timestamp TEXT
)
""")

In [28]:
# save the table creation commands
conn.commit()

In [29]:
# Query to database to confirm that the tables were created
cursor.execute("SELECT name FROM sqlite_master WHERE type='table';")
tables = cursor.fetchall()

print("Tables in the database:")
print(tables)

Tables in the database:
[('predictions_logreg',), ('predictions_rf',)]

In [30]:
# close the database connection
conn.close()

# Build two (2) predictive models using MLflow, logging hyperparameters, the model itself, four metrics, and two artifcats. Submit submit your MLflow experiments as part of your assignments

## 5. Train and log the Logistic Regression model with MLflow

In [47]:
import mlflow
import mlflow.sklearn
import matplotlib.pyplot as plt

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
    ConfusionMatrixDisplay,
)

In [33]:
# set MLflow tracking URI and experiment name
mlflow.set_tracking_uri("file:/Users/liyunxiao/Desktop/QMSS applied data analysis/takehome exercise/Take_home_exercise_4file/mlruns")
mlflow.set_experiment("f1_model_deployment")

2026/04/28 14:44:15 INFO mlflow.tracking.fluent: Experiment with name 'f1_model_deployment' does not exist. Creating a new experiment.

<Experiment: artifact_location=('file:///Users/liyunxiao/Desktop/QMSS applied data analysis/takehome '
 'exercise/Take_home_exercise_4file/mlruns/598202598880983409'), creation_time=1777401855634, experiment_id='598202598880983409', last_update_time=1777401855634, lifecycle_stage='active', name='f1_model_deployment', tags={}, trace_location=None, workspace='default'>

In [34]:
# Start an Mlflow run for logistic regression
with mlflow.start_run(run_name="logistic_regression_model") as run:
    # define and train the model
    logreg_model = LogisticRegression(
        max_iter=1000,
        solver="lbfgs",
        random_state=42
    )

    logreg_model.fit(X_train, y_train)

In [35]:
    # Generate predictions and predicted probabilities
    y_pred_logreg = logreg_model.predict(X_test)
    y_prob_logreg = logreg_model.predict_proba(X_test)[:, 1]

In [45]:
# Calculate evaluation metrics
acc_logreg = accuracy_score(y_test, y_pred_logreg)
prec_logreg = precision_score(y_test, y_pred_logreg)
rec_logreg = recall_score(y_test, y_pred_logreg)
f1_logreg = f1_score(y_test, y_pred_logreg)

In [39]:
# Log model hyperparameters
mlflow.log_param("model_type", "logistic_regression")
mlflow.log_param("max_iter", 1000)
mlflow.log_param("solver", "lbfgs")
mlflow.log_param("random_state", 42)

42

In [40]:
# Log evaluation metrics
mlflow.log_metric("accuracy", acc_logreg)
mlflow.log_metric("precision", prec_logreg)
mlflow.log_metric("recall", rec_logreg)
mlflow.log_metric("f1_score", f1_logreg)

In [41]:
# Log the trained model
mlflow.sklearn.log_model(logreg_model, "model")

2026/04/28 14:56:03 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/04/28 14:56:03 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html

In [50]:
    # Create and save a confusion matrix plot
    cm_logreg = confusion_matrix(y_test, y_pred_logreg)
    disp_logreg = ConfusionMatrixDisplay(confusion_matrix=cm_logreg)
    disp_logreg.plot()
    plt.title("Logistic Regression Confusion Matrix")
    plt.savefig("logreg_confusion_matrix.png", bbox_inches="tight")
    plt.close()
    
    # Log the confusion matrix artifact
    mlflow.log_artifact("logreg_confusion_matrix.png")

In [51]:
    # Create and save a coefficient table
    logreg_coef_df = pd.DataFrame({
        "feature": feature_cols,
        "coefficient": logreg_model.coef_[0]
    })
    
    logreg_coef_df.to_csv("logreg_coefficients.csv", index=False)
    
    # Log the coefficient table artifact
    mlflow.log_artifact("logreg_coefficients.csv")

In [52]:
    # Store the MLflow run ID for later use
    logreg_run_id = run.info.run_id

    # Print model performance
    print("Logistic Regression metrics:")
    print("Accuracy:", acc_logreg)
    print("Precision:", prec_logreg)
    print("Recall:", rec_logreg)
    print("F1 Score:", f1_logreg)
    print("Run ID:", logreg_run_id)

Logistic Regression metrics:
Accuracy: 0.9095665171898356
Precision: 0.6737967914438503
Recall: 0.5567010309278351
F1 Score: 0.6096774193548387
Run ID: e4442c20a51f42529dfce422181013b7

In [54]:
## store Logistic Regression predictions in the database
from datetime import datetime

# Build a prediction table for logistic regression
logreg_predictions = meta_test.copy()

logreg_predictions["actual_label"] = y_test.values
logreg_predictions["predicted_label"] = y_pred_logreg
logreg_predictions["predicted_probability"] = y_prob_logreg
logreg_predictions["model_name"] = "logistic_regression"
logreg_predictions["run_id"] = logreg_run_id
logreg_predictions["prediction_timestamp"] = datetime.now().isoformat()

In [55]:
import sqlite3
conn = sqlite3.connect('f1_predictions.db')

In [56]:
# Write the logistic regression predictions to the database table
logreg_predictions.to_sql(
    "predictions_logreg",
    conn,
    if_exists="append",
    index=False
)

5352

## Train and log the Random Forest model with MLflow

In [58]:
from sklearn.ensemble import RandomForestClassifier

In [60]:
# Set MLflow tracking location and experiment name
mlflow.set_tracking_uri("file:/Users/liyunxiao/Desktop/QMSS applied data analysis/takehome exercise/Take_home_exercise_4file/mlruns")
mlflow.set_experiment("f1_model_deployment")

<Experiment: artifact_location=('file:///Users/liyunxiao/Desktop/QMSS applied data analysis/takehome '
 'exercise/Take_home_exercise_4file/mlruns/598202598880983409'), creation_time=1777401855634, experiment_id='598202598880983409', last_update_time=1777401855634, lifecycle_stage='active', name='f1_model_deployment', tags={}, trace_location=None, workspace='default'>

In [62]:
mlflow.end_run()

In [ ]:
# Start an Mlflow run for random forest
with mlflow.start_run(run_name="random_forest_model") as run:
    
    #Define and train the model
    rf_model = RandomForestClassifier(
        n_estimators=100,
        max_depth=10,
        random_state=42
    )
    
    rf_model.fit(X_train, y_train)
    
    # Generate predictions and predicted probabilities
    y_pred_rf = rf_model.predict(X_test)
    y_prob_rf = rf_model.predict_proba(X_test)[:, 1]

    # Calculate evaluation metrics
    acc_rf = accuracy_score(y_test, y_pred_rf)
    prec_rf = precision_score(y_test, y_pred_rf, zero_division=0)
    rec_rf = recall_score(y_test, y_pred_rf, zero_division=0)
    f1_rf = f1_score(y_test, y_pred_rf, zero_division=0)

    # Log model hyperparameters
    mlflow.log_param("model_type", "random_forest")
    mlflow.log_param("n_estimators", 200)
    mlflow.log_param("max_depth", 8)
    mlflow.log_param("min_samples_split", 5)
    mlflow.log_param("random_state", 42)

    # Log evaluation metrics
    mlflow.log_metric("accuracy", acc_rf)
    mlflow.log_metric("precision", prec_rf)
    mlflow.log_metric("recall", rec_rf)
    mlflow.log_metric("f1_score", f1_rf)

    # Log the trained model
    mlflow.sklearn.log_model(rf_model, "model")

    # Create and save a confusion matrix plot
    cm_rf = confusion_matrix(y_test, y_pred_rf)
    disp_rf = ConfusionMatrixDisplay(confusion_matrix=cm_rf)
    disp_rf.plot()
    plt.title("Random Forest Confusion Matrix")
    plt.savefig("rf_confusion_matrix.png", bbox_inches="tight")
    plt.close()

    # Log the confusion matrix artifact
    mlflow.log_artifact("rf_confusion_matrix.png")

    # Create and save a feature importance table
    rf_importance_df = pd.DataFrame({
        "feature": feature_cols,
        "importance": rf_model.feature_importances_
    }).sort_values("importance", ascending=False)

    rf_importance_df.to_csv("rf_feature_importance.csv", index=False)

     # Log the feature importance artifact
    mlflow.log_artifact("rf_feature_importance.csv")

         # Store the MLflow run ID for later use
    rf_run_id = run.info.run_id

2026/04/28 15:42:14 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/04/28 15:42:14 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html

In [ ]:
import

In [65]:
# Convert pandas DataFrame to Spark DataFrame
predDF_final = spark.createDataFrame(rf_predictions)

NameError: name 'spark' is not defined